const locations = [
  {
    name: "Dhaka",
    areas: [
      "Jatrabari",
      "Demra",
      "Gendaria",
      "Lalbagh",
      "Azimpur",
      "Basabo",
      "Shantinagar",
      "Paltan",
      "Kalabagan",
      "Ramna",
      "Sutrapur",
      "Malibagh",
      "Kotwali",
      "Tikatoli",
      "Shahjahanpur",
      "Motijeel",
      "Wari",
      "Khilgaon",
      "Poribagh",
      "Shahbag",
      "Eskaton",
      "Kodomtoli",
      "Siddheshwari",
      "Laxmibazar",
      "Elephant Road",
      "Segunbagicha",
      "Dhanmondi",
      "Mugdapara",
      "Fakirapul",
      "Arambagh",
      "Motijheel",
      "Green Road",
      "Old Dhaka",
    ],
  },
  {
    name: "khulna",
    areas: [
      "Bagerhat",
      "Chuadanga",
      "Jashore",
      "Jhenaidah",
      "Khulna",
      "Kushtia",
      "Magura",
      "Meherpur",
      "Narail",
      "Satkhira",
    ],
  },
];

const servicesArray = [
  "AC Servicing 1-1.5 ton",
  "AC Servicing 2-3 ton",
  "AC Servicing 4-5 ton",
  "AC Servicing Basic Service",
  "AC Servicing AC Installation & Uninstallation",
  "AC Servicing Compressor fitting with gas refill",
  "AC Servicing Jet Wash",
  "AC Servicing Leak Repair",
  "AC Servicing Master Service",
  "AC Servicing Water-Drop Solution",
  "Fridge Basic Service",
  "Fridge Circuit Repair Or Replacement",
  "Fridge Compressor fitting with gas refill",
  "Fridge Condenser Fitting with gas refill",
  "Fridge Gasket change",
  "Fridge Gas refill",
  "Fridge Thermostat Replace",
  "TV Installation",
  "TV Installation",
  "TV Repair",
  "Microwave Oven Basic services",
  "Microwave Oven Buttons not working",
  "Microwave Oven Not heating",
  "Microwave Oven Sparkle/short circuit",
  "Microwave Oven Transformer replacement",
  "Water Purifier Dismantling",
  "Water Purifier Installation",
  "Water Purifier Kit replacement",
  "Water Purifier Servicing",
  "Kitchen Hood Deep cleaning",
  "Kitchen Hood Installation",
  "Kitchen Hood Repair",
  "Kitchen Hood Shifting",
  "Washing machine Basic service",
  "Washing machine Circuit repair",
  "Washing machine Gearbox repair/replace",
  "Washing machine Installation",
  "Washing machine Motor repair/replace",
  "Washing machine Water level sensor",
  "IPS IPS repair",
  "Geyser Basic",
  "Geyser Installation",
  "Generator Up to 150 KVA",
  "Generator Up to 300 KVA",
  "Generator Up to 500 KVA",
  "Gas stove Installation (Auto)",
  "Gas stove Installation (Normal)",
  "Gas stove Leak repair (Auto)",
  "Gas stove Leak repair (Normal)",
  "Gas stove Component change (Auto)",
  "Gas stove Component change (Normal)",
  "Gas stove Cleaning (Auto)",
  "Gas stove Cleaning (Normal)",
  "Oven burner Cleaning",
  "Oven burner Repair",
  "Oven burner Cleaning and repair",
  "Desktop Software/hardware checkup",
  "Desktop Windows/software installation",
  "Desktop Bios configuring/updating",
  "Desktop Data recovery",
  "Desktop Motherboard installation/repair",
  "Desktop HDD/SSD installation/replacement",
  "Desktop Full cleaning & problem identification",
  "Desktop PSU installation/repair/replace",
  "Laptop Software/hardware checkup",
  "Laptop Windows/software installation",
  "Laptop Bios configuring/updating",
  "Laptop Data recovery",
  "Laptop Motherboard installation/repair",
  "Laptop HDD/SSD installation/replacement",
  "Laptop Full cleaning & problem identification",
  "Laptop Keyboard replacement",
  "Laptop Display replacement",
  "Plumbing Plumbing checkup",
  "Plumbing Water tap installation/repair",
  "Plumbing Sink installation",
  "Plumbing Sink repair",
  "Plumbing Sink blockage",
  "Electric Electrical checkup",
  "Electric Ceiling fan repair",
  "Electric Ceiling fan coil repair",
  "Electric Ceiling fan capacitor/regulator fitting",
  "Electric Light servicing/installation",
  "Electric Circuit breaker installation",
  "Electric Circuit breaker repair/replace",
];

const keyWords = [
  "TV Mounting",
  "AC Jet Wash",
  "Refrigerator Gas refill",
  "Windows 11 Setup",
  "Oven Repair",
  "AC Basic Service",
  "Water Purifier Kit replacement",
  "AC Jet Wash",
];

const forHomeServices = [
  { title: "AC Installation", path: "/ac-logo.jpg" },
  { title: "Desktop Service", path: "/desktop.jpg" },
  { title: "Fridge Repair", path: "/fridge.webp" },
  { title: "Laptop Services", path: "/laptop-repair.jpg" },
  { title: "Oven Servicing", path: "/Oven-repair.jpg" },
  { title: "Sink Installation", path: "/Sink-reapir.jpg" },
  { title: "TV Repair", path: "/tv-repair.jpg" },
  { title: "Washing Machine Servicing", path: "/washing-machine.jpg" },
  { title: "Water Purifier Installation", path: "/water-purifier.jpg" },
];

const customerReview = [
  {
    name: "Kr Rodoshi",
    address: "Bashundhora, Dhaka",
    image: "/rodoshi.jpg",
    review:
      "Yimbs is a game-changing online service company that excels in delivering top-notch customer satisfaction. With their diverse range of services, Yimbs stands out as a versatile and reliable platform. Their user-friendly interface ensures a seamless experience. From web development and digital marketing to content creation, they offer it all. Yimbs' expert team. ",
  },
  {
    name: "Kr Rodoshi",
    address: "Bashundhora, Dhaka",
    image: "/papel.jpg",
    review:
      "Yimbs is a game-changing online service company that excels in delivering top-notch customer satisfaction. With their diverse range of services, Yimbs stands out as a versatile and reliable platform. Their user-friendly interface ensures a seamless experience. From web development and digital marketing to content creation, they offer it all. Yimbs' expert team. ",
  },
  {
    name: "Kr Rodoshi",
    address: "Bashundhora, Dhaka",
    image: "/ahad.jpg",
    review:
      "Yimbs is a game-changing online service company that excels in delivering top-notch customer satisfaction. With their diverse range of services, Yimbs stands out as a versatile and reliable platform. Their user-friendly interface ensures a seamless experience. From web development and digital marketing to content creation, they offer it all. Yimbs' expert team. ",
  },
  {
    name: "Kr Rodoshi",
    address: "Bashundhora, Dhaka",
    image: "/aysha.jpg",
    review:
      "Yimbs is a game-changing online service company that excels in delivering top-notch customer satisfaction. With their diverse range of services, Yimbs stands out as a versatile and reliable platform. Their user-friendly interface ensures a seamless experience. From web development and digital marketing to content creation, they offer it all. Yimbs' expert team. ",
  },
  {
    name: "Kr Rodoshi",
    address: "Bashundhora, Dhaka",
    image: "/papel.jpg",
    review:
      "Yimbs is a game-changing online service company that excels in delivering top-notch customer satisfaction. With their diverse range of services, Yimbs stands out as a versatile and reliable platform. Their user-friendly interface ensures a seamless experience. From web development and digital marketing to content creation, they offer it all. Yimbs' expert team. ",
  },
];

const whyYimbns = [
  "Expert Technicians with Experience",
  "warrenty on service",
  "Service at your doorstep",
  "There's no Additional Cost",
  "Assurance of Safety",
  "Propeor Diagnosis",
  "One Stop For All Service",
];

const footerlinks = [
  {
    name: "Pages",
    link: "#",
  },
  {
    name: "Blog",
    link: "#",
  },
  {
    name: "Carrer",
    link: "#",
  },
  {
    name: "Help",
    link: "#",
  },
  {
    name: "Terms of Use",
    link: "#",
  },
  {
    name: "Privacy Policy",
    link: "#",
  },
  {
    name: "Sitemap",
    link: "#",
  },
];

const footerImages = [
  "/clipArts/facebook.jpg",
  "/clipArts/instagram.png",
  "/clipArts/twitter.png",
  "/clipArts/linkedin.png",
  "/clipArts/youtube.png",
];

export {
  locations,
  servicesArray,
  keyWords,
  forHomeServices,
  customerReview,
  whyYimbns,
  footerlinks,
  footerImages,
};
